sylius_twig_hooks:
  hooks:
    'sylius_admin.common.create.content.form.sections.general':
      default:
        template: '@SyliusEasyCrudPlugin/shared/crud/common/content/form/sections/general/default.html.twig'
        priority: 0
    'sylius_admin.common.update.content.form.sections.general':
      default:
        template: '@SyliusEasyCrudPlugin/shared/crud/common/content/form/sections/general/default.html.twig'
        priority: 0
    'sylius_admin.common.update.content.header.title_block.actions':
      easy_crud_actions:
        template: "@SyliusEasyCrudPlugin/crud/action/_actions.html.twig"
        priority: 250
