services:

  Adeliom\SyliusEasyCrudPlugin\Maker\CreateEasyCrud:
    tags: [ 'maker.command' ]
    arguments:
      - "@doctrine"
      - "@parameter_bag"

  Adeliom\SyliusEasyCrudPlugin\Maker\CreateEntity:
    tags: [ 'maker.command' ]
    arguments:
      - "@doctrine"
      - "@parameter_bag"
