services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Adeliom\SyliusEasyCrudPlugin\Maker\CreateEasyCrud:
    tags: [ 'maker.command' ]
    public: true
    arguments:
      - "@doctrine"
      - "@parameter_bag"

  Adeliom\SyliusEasyCrudPlugin\Maker\CreateEntity:
    tags: [ 'maker.command' ]
    public: true
    arguments:
      - "@doctrine"
      - "@parameter_bag"
